# Test your FastAPI endpoints
###
POST http://127.0.0.1:8000/auth/signup
Content-Type: application/x-www-form-urlencoded

login=ab&password=abo&password2=abo
###
POST http://127.0.0.1:8000/auth/signup
Content-Type: application/x-www-form-urlencoded

login=aboba&password=aboba&password2=abob
###
POST http://127.0.0.1:8000/auth/signup
Content-Type: application/x-www-form-urlencoded

login=abobas&password=aboba&password2=abobad
###
POST http://127.0.0.1:8000/auth/signup
Content-Type: application/x-www-form-urlencoded

login=abobas&password=aboba&password3=abobad